openshift_cluster_content:
- object: projects
  content:
  - name: "create environments"
    file: "{{ inventory_dir }}/../projects/projects.yml"
    file_action: create
- object: deployments
  content:
  - name: "deploy dev environment"
    template: "{{ inventory_dir }}/../templates/deployment.yml"
    params: "{{ inventory_dir }}/../params/deployment-dev"
  - name: "deply stage environment"
    template: "{{ inventory_dir }}/../templates/deployment.yml"
    params: "{{ inventory_dir }}/../params/deployment-stage"
  - name: "deply prod environment"
    template: "{{ inventory_dir }}/../templates/deployment.yml"
    params: "{{ inventory_dir }}/../params/deployment-prod"
- object: builds
  content:
  - name: "deploy build pipeline to dev"
    template: "{{ inventory_dir }}/../templates/build.yml"
    params: "{{ inventory_dir }}/../params/build-dev"
