apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectpipelines.cop.redhat.com
spec:
  group: cop.redhat.com
  names:
    kind: ProjectPipeline
    listKind: ProjectPipelineList
    plural: projectpipelines
    singular: projectpipeline
  scope: Cluster
  version: v1alpha1